#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1-100
#Displays FizzBuzz when the number is a multiple of 3 and 5 
#Displays Fizz when the number is multiple of 3
#Displays Buzz when the number is a multiple of 5
#Otherwise, displays the number
#In a list format
x=1
while [ $x -le 100 ]
do
	if (( x % 3 == 0 )) && (( x % 5 == 0 ))
	then 
		echo "FizzBuzz"
	((x++))
	elif (( x % 3 == 0 )) && [ $(( x % 5 )) -ne 0 ]
	then
		echo "Fizz"
	((x++))
	elif (( x % 5 == 0 )) && [ $(( x % 3 )) -ne 0 ]
	then
		echo "Buzz"
	((x++))
	elif [ $x -gt 100 ]
	then
		break
	else
	echo "$x"
	((x++))
fi
done
