#!/usr/bin/env bash
# This script will display numbers from 1 to 20 and:
# "4 bad luck from China" for the 4th iteration
# "9 bad luck from Japan" for the 9th iteration
# "17 bad luck from Italy" for the 17th iteration
i="1"
while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
	esac
	((i++))
done
